### ISSUE TITLE
Order in single view of A-Z wrong

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_adresslist#1]
The sorting order is not correct. If you choose from a letter A-Z there is a listing of all firms displayed. After choosing one letter the firms are not correctly sorted from A-Z. 

Example: 
https://www.region-emmental.ch/de/firmenliste-a-z/B///controller/list/#jump

Can you fix this on github?

Thanks.

regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

We have downloaded all the files, But it seems some files are missing or updated, So it doesn't show output on the front end. 

Can you please give us the access details of the site - https://www.region-emmental.ch/ 

So that we can check it directly?

Let me know your feedback for the same.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh
YES. I will send you the access in a few minutes by mail. THX.
Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

- Sorting order
Status > Done
Screenshot > http://prntscr.com/bv8z6u
Comment > We have resolve this directly on the server - https://www.region-emmental.ch/

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh
thanks. Works. 
Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

I have received an Email regarding the issue in this Extension, From here - http://ticket.netconsult.ch/index.php?id=300&tx_ketroubletickets_pi1%5BshowUid%5D=48
Can you please tell me is there still any bug after our update? And if so can you please give me some more details on this?

Thanks in advance.

Regards.

**Comment by angeloprevitali** [comment]
That was from our Ticket System. I just closed this on our ticket System.
Regards,
Angelo

**Comment by angeloprevitali** [comment]
Please check open issues just on GitHub. The link you sent me was NOT applicable to this issue here on gitHub. Please check.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your message.

Okay I got your point.  I will take care from next time.

Regards.
Thanks.
