### ISSUE TITLE
Compatibility to version 8.7 LTS not completely 

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_adresslist#10]
Hello Jignesh

as we saw in the install tool there leads still some compatibility things that should befixed for version 8.7. Can you still fix those? See printscreen.

![screenshot_1](https://cloud.githubusercontent.com/assets/17588253/25574136/c69abad6-2e4b-11e7-8f9b-79978d34ce2f.png)

Thanks.

Please upload afterthat the final version directly on GitHub.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Afternoon!

Thank you for your message. I hope you had a nice weekend.
**Status:** Done 
**Screenshot:** http://prntscr.com/f2tlen, http://prntscr.com/f2tku1

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

great, thanks. Wish you a nice evening!

Best regards,
Angelo
