### ISSUE TITLE
Cleanup hardcoded PID's and URLs

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_adresslist#2]
In this extension there are a lot of hardcoded things that should not be.

A lot of hardcoded PID's to links, URL's and hardcoded https:// + http:// links which will not work anymore if the website URL gets changed.

Thanks for fix and review the whole extension.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status:** Done
**Comment:** We have removed all the hardcoded URLs from the extension. You can review it from your end too.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

the hardcoded URL will still not work if the website gets used with SSL (https:). Can you fix this?

<a target="_blank" href="**http:**//{key.internet_adresse}">{key.internet_adresse}</a>

Plus how can you set up the URL for this variable? There seems to be something completely new... Isn't there a better gloablly solution for this instead of using another key to set up just a domain?

{key.internet_adresse}

Thanks for fixing this.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your feedback/reply. 
We will check this and get back to you asap.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good afternoon!

**1.** Hard coded URL
**Status:** Done
**Comment:** Please check now. The change in HTTP request will be there for both HTTP and HTTPS.

**2.** Google map
**Comment:** Can you please check this again? We haven't found this issue. Right now it's working with both HTTP and HTTPS. 

**3.** {key.internet_adresse}
**Comment**: Are you talking about this field - http://prntscr.com/es9qhz If so this field is used to store the external URL.
Beck-end: http://prntscr.com/es9l40
Front-end: http://prntscr.com/es9ln5
External URL: http://prntscr.com/es9mop
Are you finding any issue with it?

Don't hesitate to ask if you have any query.

Regards.
Thank You.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Noon!

Thank you for your message.

#1
**Status:** Done
**Screenshot:** http://prntscr.com/eslwl4

#2 Okay.

#3 Okay.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

by installing the EXT: on a TYPO3 CMS version 8.7.1 the compatibility message gets an error that the EXT isn't compatible with 8.7. Can you fix this?

Plus, after installing the EXT on a 8.7.1 we got the following errors:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'DELETE FROM `cf_extbase_object` WHERE `identifier` = ?' with params ["54672acf56e913fcba34f51662cf8320"]: Prepared statement needs to be re-prepared | Doctrine\DBAL\Exception\DriverException thrown in file /home/httpd/vhosts/netconsult.ch/t8fluid2.edorf.ch/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 115. Requested URL: https://t8fluid2.edorf.ch/typo3/index.php?M=tools_ExtensionmanagerExtensionmanager&moduleToken=834233121fe9549be612c145320d766114cd7919&tx_extensionmanager_tools_extensionmanagerextensionmanager%5BrefreshModuleMenu%5D=1&tx_extensionmanager_tools_extensionmanagerextensionmanager%5BrefreshTopbar%5D=1&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Baction%5D=index&tx_extensionmanager_tools_extensionmanagerextensionmanager%5Bcontroller%5D=List `

I thought it will work on a 8.7 already... Seems not to be fully adapted, yet?

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you very much for your message. Let's check all your mentioned points and we will get back to you soon.

Regards.
Thank You.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Evening!

Please find our comments as below.

#Compatibility to 8.7.1
**Status**: Done
**Comment**: Actually, When we have worked on this and given update at that time TYPO3 8.7.1 was not introduced. That's why you were receiving the error message.
Fyi, We must give version range in extension so if any new TYPO3 version release and we implement same extension then it's show warning during installation. We have to add the version compatibility in the extension.

#After installing the EXT on a 8.7.1 we got the following errors:
**Status**: Query
**Comment:** We have checked error, But not able to find this. We have checked it here: http://t8.edorf.ch/ and also checked in our local site. but not able to find this. 
See this screenshots
FE: http://prntscr.com/f0lp79
BE: http://prntscr.com/f0lput

If you still find this issue, Then can you please send us further more details for this?

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

Ok. Maybe it is from another extension...? Well, let it be. I think until it works we will let it be.

One favor: Could you please MERGE! your version of the EXT:netc_addresslist on GitHub please?

Be aware: I made some little changes in language files and FE templates... but by MERGING the EXT you will see it. I don't think there would be some problems...

Can you confirm me this afterfinishing it?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message.

#Merge last changes. 
Yes, We have uploaded all our changes to Github and checked all working fine. Although please check it from your end also.

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

by adding the compatibility to 8.7.0-8.7.1 with the next update we get another error by installing the extension regulary. Why this minor version? Do you think that the EXT:netc_addresslist won't work anymore correctly with higher versions? Or what is the reason why you put it on dependency until 8.7.1 in emconf.php file? I think that we can put version to 8.7.99. What do you think? Or do you see any problems coming here?

Thanks for answer.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Evening!

Thank you very much for your message. 

Yes, you are absolutely right. We were missed to add this compatibility. But now we have added this. See these screenshots: http://prntscr.com/f2uu5t, http://prnt.sc/f2us9t

Please let's know if you need any kind of support on this.

Have a nice day ahead.
Regards.

**Comment by angeloprevitali** [comment]
Hi Jignesh

that's ok, thanks. 

Regards,
Angelo.
