### ISSUE TITLE
BE: Add fields in constants for single pages and configuration

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_adresslist#4]
Currently every PID for pages and sys_folders in extension are hardcoded. 

Could you please adapt the source like this that every single hardcoded ID could be set upped in EXT: in the constants of the TYPO3 in a single field? In example a field to be set upped in constants for the details page of a certain view and so on.

Thank you very much.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

**Status:** Done
**Comment:** We have removed all the static PIDs from the extension. You can review it from your end too.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

thanks for your work. The adapting from static PID's looks good.

As I see this thing looks fine and I will close this ticket.

Regards,
Angelo
