### ISSUE TITLE
Add compatibility to TYPO3 CMS version 7.6 + 8.6 and higher.

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_adresslist#5]
Can you please adapt the extension for compatibility of TYPO3 CMS versions 7.6 and 8.6 and higher?

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Eveneing!

I hope you are doing good.

Can you please provide us Live server as well as Dev server details? So that we can get the latest code and work on it in Local and give you update over dev server.

Awaiting for your response here.
Have a nice day and a great weekend ahead. Regards!

**Comment by angeloprevitali** [comment]
Guten Tag

Ich bin bis und mit Sonntag, 19. Februar 2017 abwesend. 

Ihr E-Mail wird nicht weitergeleitet und erst am Montag, 20. Januar 2017 gelesen.

In dringenden Fällen kontaktieren Sie Herr Ernest Peter (ernest.peter@netconsult.ch, Tel.  031 352 01 48).

Besten Dank.


Freundliche Grüsse
Angelo Previtali

Angelo Previtali
TYPO3 CMS Integrator

NetConsult AG
Buristrasse 21, 3006 Bern
Tel. 031 352 01 48
angelo.previtali@netconsult.ch
www.netconsult.ch

**Comment by angeloprevitali** [comment]
Hello Jignesh

shure! I will duplicate our actual V8.6 and send you the access data and the FTP.

Regards,
Angleo

**Comment by angeloprevitali** [comment]
I sent you the access data by mail.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message. Yes, the last details are working correctly.
Can you please also send us the current working Live server details? Or any dev server details where we can compare the new and current working flow with actual data?

We have these details but it seems not working anymore.

FTP: www.region-emmental.ch
User: sanjay
Pass: D7Ab%w435379
 
http://www.region-emmental.ch/typo3 is the same as usual with username „sanjay“ and password as used in all the others projects.

Awaiting for your response here.

Regards.

**Comment by angeloprevitali** [comment]
I will duplicate the actual website and send you the access data by mail.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you very much for your reply. Sure we will wait for the details.

Have a nice day ahead. Thanks!

**Comment by angeloprevitali** [comment]
I just sent you the informations needed by mail.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Afternoon!

#Extension Compatibility with TYPO3 8
**Status:** Done
**Comment:** We have added the compatibility to TYPO3 8. You can review it here: http://t8.edorf.ch/de/startseite/

**Note:** There are lot's of changes the last version of Extension from Github and your dev server, So we have decided to go with the last code that you have replicated from the Live site. So once you confirm this you have to replace the last final code in Github.

Please review all functions on the Dev server.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

thanks for your feedback. We well check this extension in detail as soon as possible on the dev plattform of t8.edorf.ch. But what we saw already is, that the TCS Tables are still not fully V8 compatible. See log in install tool (copied below).

Can you please recheck and fix those issues, too?

Thanks.

Best reagrds,
Angelo


Changed showitem string of TCA table "tx_netcadresslist_domain_model_address" type "1" due to changed field "sys_language_uid".

Changed showitem string of TCA table "tx_netcadresslist_domain_model_business" type "1" due to changed field "sys_language_uid".

Changed showitem string of TCA table "tx_netcadresslist_domain_model_category" type "1" due to changed field "sys_language_uid".

Migrated TCA table "tx_netcadresslist_domain_model_address" showitem field of type "1": Moved additional palette with name "1" as 3rd argument of field "hidden" to an own palette. The result of this part is: "hidden, --palette--;;1"

Migrated TCA table "tx_netcadresslist_domain_model_business" showitem field of type "1": Moved additional palette with name "1" as 3rd argument of field "hidden" to an own palette. The result of this part is: "hidden, --palette--;;1"

Migrated TCA table "tx_netcadresslist_domain_model_category" showitem field of type "1": Moved additional palette with name "1" as 3rd argument of field "hidden" to an own palette. The result of this part is: "hidden, --palette--;;1"

[tx_netcadresslist_domain_model_address.ctrl.iconfile] relative path to ../typo3conf/ext/ is deprecated, use EXT: instead

[tx_netcadresslist_domain_model_business.ctrl.iconfile] relative path to ../typo3conf/ext/ is deprecated, use EXT: instead

[tx_netcadresslist_domain_model_category.ctrl.iconfile] relative path to ../typo3conf/ext/ is deprecated, use EXT: instead

Using select fields without the "renderType" setting is deprecated in table "tx_netcadresslist_domain_model_address" and column "true_category_click"

Using select fields without the "renderType" setting is deprecated in table "tx_netcadresslist_domain_model_address" and column "business"

The TCA setting 'versioningWS' was set to a boolean value in TCA tx_netcadresslist_domain_model_address['ctrl']['versioningWS']

The TCA setting 'versioning_followPages' was removed as it is unused in TCA tx_netcadresslist_domain_model_address['ctrl']['versioning_followPages']

The TCA setting 'versioningWS' was set to a boolean value in TCA tx_netcadresslist_domain_model_business['ctrl']['versioningWS']

The TCA setting 'versioning_followPages' was removed as it is unused in TCA tx_netcadresslist_domain_model_business['ctrl']['versioning_followPages']

The TCA setting 'versioningWS' was set to a boolean value in TCA tx_netcadresslist_domain_model_category['ctrl']['versioningWS']

The TCA setting 'versioning_followPages' was removed as it is unused in TCA tx_netcadresslist_domain_model_category['ctrl']['versioning_followPages']

The TCA setting 'versioningWS' was set to a boolean value in TCA tx_netcbakerlist_domain_model_addresses['ctrl']['versioningWS']

The TCA setting 'versioning_followPages' was removed as it is unused in TCA tx_netcbakerlist_domain_model_addresses['ctrl']['versioning_followPages']

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_netcadresslist_domain_model_address['columns']['starttime']['l10n_mode'] and changed to tx_netcadresslist_domain_model_address['columns']['starttime']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_netcadresslist_domain_model_address['columns']['endtime']['l10n_mode'] and changed to tx_netcadresslist_domain_model_address['columns']['endtime']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_netcadresslist_domain_model_business['columns']['starttime']['l10n_mode'] and changed to tx_netcadresslist_domain_model_business['columns']['starttime']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_netcadresslist_domain_model_business['columns']['endtime']['l10n_mode'] and changed to tx_netcadresslist_domain_model_business['columns']['endtime']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_netcadresslist_domain_model_category['columns']['starttime']['l10n_mode'] and changed to tx_netcadresslist_domain_model_category['columns']['starttime']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_netcadresslist_domain_model_category['columns']['endtime']['l10n_mode'] and changed to tx_netcadresslist_domain_model_category['columns']['endtime']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_netcbakerlist_domain_model_addresses['columns']['starttime']['l10n_mode'] and changed to tx_netcbakerlist_domain_model_addresses['columns']['starttime']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_netcbakerlist_domain_model_addresses['columns']['endtime']['l10n_mode'] and changed to tx_netcbakerlist_domain_model_addresses['columns']['endtime']['behaviour']['allowLanguageSynchronization'] = true

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Thank you for your feedback/reply. 
We will check this and get back to you asap.

Regards.

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

#Adapt TCS Tables to be compatible for TYPO3 V8
**Status**: Done
**Screenshot**: http://prnt.sc/ervjxm

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

ok, thanks. Look fine now.

Regards,
Angelo
