### ISSUE TITLE
Compatibility of extension

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_adresslist#6]
Hello Jignesh

i installed the EXT:netc_ubidb (which is not this project od netc_addresslist normally) on the dev server of t8.edorf.ch because you wrote me on the ticket https://github.com/NetConsultAG/netc_ubidb/issues/9 that this extension works with TYPO3 8.6. I installed it to check this but now it gets an error in the EM due to incompatibility of this extension that seems not to be compatible. Can you check what's the problem is?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

Thank you for your message.

It seems you have added this ticket by mistake here. We have already given our comment/update here: https://github.com/NetConsultAG/netc_ubidb/issues/11

Regards.
