### ISSUE TITLE
Bug: If creating multiple Sys Folders with Branches

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_adresslist#7]
If you create multiple sys folders with different branches inside suddenly every sys folder gets the branches of the other sys folder displayed, too in the BE to choose from.

On the 6.2-version it wasen't like this. The branches gets respected by sys folder.

Is this any bug from upgrading to 8.7.?

![screenshot_1](https://cloud.githubusercontent.com/assets/17588253/25342666/fcba078c-290c-11e7-96eb-32a14d725b59.png)

in the bough of sys folders there are the sum of every braches. even if they were created sys folder by sys folder...

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Screenshots: http://prntscr.com/f0l1lq, http://prntscr.com/f0l26u

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

that works now, thanks.

Regards,
Angelo.
