### ISSUE TITLE
Revised version with adapted XLF texts uploaded on gitHub

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_adresslist#8]
Hi Jignesh

we adapted some HTML and text in XLF and I uploaded it on GitHub.
could you please merge your adapted version as soon all fixes are made?

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 
Good Morning!

#Merge last changes. 
Yes, We have uploaded all our changes to Github and checked all working fine. Although please check it from your end also.

Regards.

**Comment by angeloprevitali** [comment]
Hello Jignesh

thanks.

That's ok.

Regards,
Angelo
