### ISSUE TITLE
Plug-In Description 

### ISSUE THREAD

**Issue by angeloprevitali** [NetConsultAG/netc_adresslist#9]
Could you please change the actual text of the Plug-In from "address" to netc_addresslist? Like this we know it immediately which EXT was inserted like you do on all other EXT developings?

![screenshot_2](https://cloud.githubusercontent.com/assets/17588253/25343671/fe7bd002-290f-11e7-9407-99a345a5ece5.png)

Thanks.

Regards,
Angelo

**Comment by jigneshnitsan** [comment]
Hello @angeloprevitali 

Status: Done
Screenshot: http://prnt.sc/f0kjt4

Regards.
Thank You.

**Comment by angeloprevitali** [comment]
Hello Jignesh

that works. Thanks.

Regards,
Angelo.
